### ISSUE TITLE
Proposal for a label-based syntax and much more

### ISSUE THREAD

**Issue by ejaa3** [Relm4/Relm4#450] opened 2023-04-12 05:14 UTC
As may be known, Rust supports [`'labels`](https://doc.rust-lang.org/rust-by-example/flow_control/loop/nested.html) (they are not lifetimes) and I see that using labels reduces visual noise and saves code lines. Regarding syntax highlighting, I've attached images of the pseudocode with better syntax highlighting than GitHub, as well as the original sources to test the highlighting for yourself. Perhaps it is better to look at the images before:

- [syntax_highlighted.png](https://user-images.githubusercontent.com/108014240/231354136-63b13299-d2ac-41ab-b9d1-2b60fd29c224.png)
- [with_guidelines.svg](https://user-images.githubusercontent.com/108014240/231354297-c12f7a05-23ee-43ff-b6c2-4b1e33ecbb4c.svg) (you may have to download it and use an image viewer).
- [new-syntax.rs.txt](https://github.com/Relm4/Relm4/files/11207329/new-syntax.rs.txt)
- [old-syntax.rs.txt](https://github.com/Relm4/Relm4/files/11207330/old-syntax.rs.txt)
- [syntax_issue.md.txt](https://github.com/Relm4/Relm4/files/11207416/syntax_issue.md.txt)

`rust.rs.txt` files should have the `.txt` removed from their name if downloaded, and I'm fine with KSyntaxHighlighting (I've tried KWrite), the one from VS Code and GtkSourceView (I've tried GNOME Text Editor).

For example, instead of writing:

~~~ rust
#[name(flap)]
adw::Flap {
	#[wrap(Some)]
	#[name = "sidebar"]
	set_flap = &adw::Bin::default() { },
	
	#[wrap(Some)]
	#[name = "content"]
	set_content = &adw::Bin { },
}
~~~

Could be written:

~~~ rust
adw::Flap 'name flap {
	set_flap = &adw::Bin::default() 'name sidebar 'wrap Some { },
	
	set_content = &adw::Bin 'name content 'wrap Some { },
}
~~~

And probably leave `#[this syntax]` for authentic attributes:

~~~ rust
adw::ApplicationWindow {
	#[cfg(debug_assertions)] // Easy to implement.
	add_css_class: "devel", // https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/style-classes.html#development-window
	
	adw::Flap 'name flap {
		#[cfg(feature = "with_sidebar")] // Very hard to implement and usually unnecessary.
		set_flap = &adw::Bin 'name sidebar 'wrap Some { },
		// ...
	}
}
~~~

## Naming

Currently things can be named in three ways:

~~~ rust
gtk::Box {
	#[name(widget)]
	adw::Bin { },
	
	#[name = "widget"]
	adw::Bin { },
	
	append: widget = adw::Bin { },
}
~~~

The idea is to obsolete them all in favor of `'name widget` as in the previous example.

## Local variables

~~~ rust
gtk::Box {
	#[local]
	local_bin -> adw::Bin { },
	
	#[local_ref]
	local_ref_bin -> adw::Bin { },
}
~~~

Could be written:

~~~ rust
gtk::Box {
	adw::Bin 'local local_bin { },
	
	adw::Bin 'local_ref local_ref_bin { },
}
~~~

I still don't understand procedural macros, so for implementation reasons perhaps one of the following alternatives is preferable, which seem less cool to me:

~~~ rust
gtk::Box {
	// "append =" to distinguish the first from the last
	append = 'local local_bin adw::Bin { },
	append = 'local local_bin @ adw::Bin { },
	
	'local local_bin // new line if you will
	append = adw::Bin { },
}
~~~

`'name`, `'local`, and `'local_ref` cannot go together.

## Updating the view

~~~ rust
gtk::Label {
	#[watch]
	set_label: &format!("Count: {}", model.counter),
	
	#[watch(skip_init)]
	set_label: &format!("Count: {}", model.counter),
	
	#[track(model.counter_changed)]
	set_label: &format!("Count: {}", model.counter),
	
	#[track(skip_init, model.counter_changed)]
	set_label: &format!("Count: {}", model.counter),
}
~~~

Could be written:

~~~ rust
gtk::Label {
	'update set_label: &format!("Count: {}", model.counter),
	
	'update_lazy set_label: &format!("Count: {}", model.counter),
	
	'update if model.counter_changed() @
	set_label: &format!("Count: {}", model.counter),
	
	'update_lazy if model.counter_changed() @
	set_label: &format!("Count: {}", model.counter),
}
~~~

Some notes:

- The @ sign indicates the end of the conditional expression (if it is possible to avoid it, it would be great).

- I write `'update` because it is allusive to the `update_view()` method.

- I write `_lazy` instead of something like `_after_init` because it is shorter, and while `_after_init` is explicit in terms of implementation, `_lazy` is explicit in that the data being used in the conditional expression should be data that is lazily initialized (such as an `OnceCell<T>` or a `Rc<RefCell<Option<T>>>`).

## Returned data.

Instead of writing:

~~~ rust
gtk::Stack {
	add_child = &adw::Bin {
		gtk::Label { },
	} -> { // can the returned data be named?
		set_name: "my_child",
	},
}
~~~

Could be written:

~~~ rust
gtk::Stack {
	add_child = &adw::Bin {
		'returns { set_name: "my_child" },
		// 'returns can be located anywhere within scope, but it is only declared once.
		gtk::Label { },
	},
}
~~~

I think it is necessary to specify the method for `'returns` to work (in this case `add_child = `), but if it is possible to avoid it would be great.

The biggest advantage of `'returns` is that you can assign properties to the returned data at the beginning of the scope, which is easier to read.

To name the returned data, I think it is necessary to specify the type of the returned data first. The syntax would be:

~~~ rust
'returns gtk::StackPage 'name my_page {
	set_name: "my_child",
},
~~~

Finally, you may want to edit only on the returned data. For example, this is currently possible:

~~~ rust
adw::Leaflet {
	property_expression = str::as_ref("folded") { } -> {
		bind["show-end-title-buttons", glib::Object::NONE]: &left_header_bar,
		bind["visible", glib::Object::NONE]: &back_button,
		bind["visible", glib::Object::NONE]: &forward_button,
	},
},
~~~

In this case, the method is not called with `=`, but with `:` and then the label as follows:

~~~ rust
adw::Leaflet {
	property_expression: "folded" 'returns {
		bind["show-end-title-buttons", glib::Object::NONE]: &left_header_bar,
		bind["visible", glib::Object::NONE]: &back_button,
		bind["visible", glib::Object::NONE]: &forward_button,
	},
},
~~~

`'returns` is needed to be explicit (the data being edited is the returned data, not the string), and I think it avoids colliding with an inline struct definition. For example:

~~~ rust
Something {
	set_struct: MyStruct { field: "value" } 'returns {
		struct_method: "hi"
	},
},
~~~

The same should work with multiple arguments:

~~~ rust
Something {
	method["args"]: ("id", 3) 'returns ReturnType 'name data {
		method: "hi",
	}
}
~~~

## Chains

Instead of writing:

~~~ rust
gtk::ToggleButton {
	#[chain(bidirectional().sync_create().build())]
	bind_property[&flap, "reveal-flap"]: "active",
}
~~~

Could be written:

~~~ rust
gtk::ToggleButton {
	'chain bidirectional().sync_create().build() @
	bind_property[&flap, "reveal-flap"]: "active",
}
~~~

Perhaps `'chain` and `'returns` cannot go together.

## Templates:

Instead of writing:

~~~ rust
#[name = "template"] // I guess it can be named
#[template]
MyTemplate {
	#[name = "child"] // I guess it can be named
	#[template_child]
	a_child {
		adw::Bin { },
	},
}
~~~

Could be written:

~~~ rust
'template MyTemplate 'name parent {
	'template_child a_child 'name child {
		adw::Bin { },
	},
}
~~~

An alternative would be:

~~~ rust
MyTemplate 'name parent 'template {
	a_child 'name child 'template_child {
		adw::Bin { },
	},
}
~~~

I prefer the first, but there should not be two tags together like:

~~~ rust
MyTemplate 'template 'name parent { }
~~~

## Root widget

Instead of writing:

~~~ rust
view! {
	#[root]
	adw::ApplicationWindow { }
	
	#[local]
	non_root -> adw::Bin { }
}
~~~

Could be written:

~~~ rust
view! {
	// use the same name as the &Self::Root parameter
	adw::ApplicationWindow 'name root { }
	adw::Bin 'local non_root { }
}

fn init(init: Self::Init,
        root: &Self::Root, // the parameter
      sender: ComponentSender<Self>) -> ComponentParts<Self> { ... }
~~~

In case a `#[root]` is required, the alternatives are:

~~~ rust
'root adw::ApplicationWindow 'name optional_name { } // I prefer this
adw::ApplicationWindow 'name optional_name 'root { }

// avoid having two labels together:
adw::ApplicationWindow 'root 'name optional_name { }
~~~

## Conditional initialization

Currently `if [let?] else` and `match` are being used to create a `gtk::Stack`, which is absolutely unexpected but visually looks as expected. While fields can be updatable (watched or tracked), all widgets are always created and the condition is always tested in `update_view()`, even in cases where you only wanted to create a widget under a condition. So I think it's better to deprecate that implementation and do the same in the explicit and traditional way. That is, instead of writing:

~~~ rust
#[transition(SlideLeft)]
if model.counter % 2 == 0 {
	gtk::Label {
		set_label: "Value is even",
	}
} else {
	gtk::Label {
		#[watch]
		set_label: &format!("Value is {}", model.counter),
	},
}
~~~

Rather write (with the new syntax):

~~~ rust
gtk::Stack {
	set_transition_type: gtk::StackTransitionType::SlideLeft
	
	gtk::Label 'name first {
		set_label: "Value is even",
	},
	
	gtk::Label 'name second {
		'update set_label: &format!("Value is {}", model.counter),
	},
	
	'update set_visible_child:
		if model.counter % 2 == 0 { &first } else { &second },
}
~~~

Now you can leave `if [let] else` and `match` to assign methods or add widgets conditionally, which would be incompatible with some keywords like `'name` and `'update`, but still very necessary, especially in factories whose model requires using specific widgets and even sending a different message to the parent component. For example, for the following model:

~~~ rust
enum DataType { Bool(bool), Number(i32), String(String) }

struct Model {
	data_name: String,
	data_type: DataType
}
~~~

The view could be initialized like this:

~~~ rust
gtk::Box {
	gtk::Label { set_label: &model.data_name },
	
	#[cfg(feature = "something")] // in this case the attributes should be easy to implement
	match model.data_type {
		DataType::Bool(value) => gtk::Switch 'local my_switch {
			set_active: value, // 'local and 'local_ref should work, perhaps in non-factories.
		},
		DataType::Number(value) => gtk::SpinButton {
			set_value: value as f64,
		},
		DataType::String(value) => {
			add_css_class: "linked", // https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/style-classes.html#linked-controls
			gtk::Entry { set_text: &value },
			gtk::Button { set_label: "Clear" },
		}
	}
}
~~~

## Finally...

Sometimes the return type of a method is not known, for which the following syntax is used:

~~~ rust
model.widget.as_ref() -> &gtk::Widget {
	set_valign: gtk::Align::Center,
}
~~~

I like it, although it seems like a cast, so an intuitive alternative would be to use `as` instead of `->`:

~~~ rust
model.widget.as_ref() as &gtk::Widget {
	set_valign: gtk::Align::Center,
}
~~~

**Comment by AaronErhardt** [comment] 2023-04-12 08:33
Some notes from my side:

#### New attribute syntax

I personally prefer `@` over `'` because `@` seems to used more commonly in macros and looks more natural to me. But this is easy to change later anyway, so we can decide on this later.

What is more problematic is the use of attributes sometimes before, sometimes after the widget or property:

```rust
adw::Flap 'name flap {}
append = 'local local_bin adw::Bin { }
'update set_label: &format!("Count: {}", model.counter)
'returns gtk::StackPage 'name my_page {}
```

Putting attributes always ahead of the widget or property has made parsing a breeze and is also very consistent for users.
I  would prefer something like this:

```rust
'name flap
adw::Flap {}

'local local_bin
append = adw::Bin { }

'update
set_label: &format!("Count: {}", model.counter)

'name my_page
returns gtk::StackPage {}
```

Note that `returns` is not an attribute anymore because IMO it doesn't make sense to make it an attribute.
We should rather use it like a keyword.

#### Macro syntax

> The @ sign indicates the end of the conditional expression (if it is possible to avoid it, it would be great).

Yes, it should be easy to avoid this. Proc-macros can parse literally raw tokens, so as soon as the preview expression ends and no `'` is there, we know that this is a new method call.

#### Regarding conditional widgets

> So I think it's better to deprecate that implementation and do the same in the explicit and traditional way.

This is not the whole story. You can easily write code like this with the conditional syntax:

```rust
if let Some(value) = &model.counter {
    gtk::Label {
        #[watch]
        set_label: &format("Value: {}", value),
    }
} else {
    // second page...
}
```

With your proposed syntax, this would be considerably more complicated.
If I used a match statement the difference would become even more clear.

```rust
gtk::Stack {
    gtk::Label 'name first {
        'update if model.counter.is_some()
        set_label: &format("Value: {}", model.counter.unwrap()),
	},
	
    // second page...
	
    'update set_visible_child:
        if model.counter.is_some() { &first } else { &second },
}
```

Your suggestion for changing the syntax to be only for initialization seems to lack a solution for updating values.
If you want to keep the button in sync with `DataType::Bool(value)`, you have to make sure that the user never uses another variant of `DataType` in their model, otherwise you might suddenly need the `gtk::SpinButton` for the `DataType::Number(value)` variant, which wasn't created in the first place.

```rust
gtk::Box {
    match model.data_type {
        DataType::Bool(value) => gtk::Switch 'local my_switch {
            // How do you want to access or update this value???
            set_active: value,
        },
        DataType::Number(value) => gtk::SpinButton {
            set_value: value as f64,
        },
        // ...
    }
}
```

What I could imagine though, would be to use lazy initialization for conditional widgets. We could generate functions to generate initialize each conditional widget and only create them when they are needed. This, however would mostly make the macro code generation a lot more complicated and also has some implications for the generated `Widgets` struct because the named widgets do not have the correct type anymore (basically `SomeWrapper(gtk::Label)` instead of `gtk::Label`). Additionally, nested conditional widgets make this approach more complicated.

#### Widget type

> I like it, although it seems like a cast, so an intuitive alternative would be to use as instead of ->:

It is not a cast though, so `->` has a better semantic meaning IMO.

**Comment by ejaa3** [comment] 2023-04-13 03:24
I wanted to answer early but there was no light. Anyway...

## The legendary battle of `'` vs `@`

I know you said this could be decided later, but I want to leave a sneak peek. Some of the reasons to use `'` instead of `@` are:

1. The syntax of `'this` is more likely to be fully highlighted than `@this`. I actually started with `@this`, but to increase the chances of having it highlighted (because it's practically 0) I had to `@put(parens)` (almost all `@keywords` have an argument).

2. In `@this(case)`, the symbols `@`, `(` and `)` make more noise than a `'` without parentheses, and also the word is highlighted as if it were a function call, whereas `'this` is highlighted for what it is, a `'label`, or `'lifetime` but in Rust they are also used as labels. For example:

~~~ rust
let data = 'label: { break 'label Some("label") };
~~~

3. In the macro `view!` there are almost no (or even no) labels or lifetimes, so using `'labels` is advantageous when the syntax highlighter theme has a specific color for `'labels`, which differs from function calls, rust keywords, methods, etc. In the images that I sent you can distinguish only by the color the `'labels` from the rest of the things inside the macro.

In case you still prefer `@this` (without parentheses), there might still be a feature that lets you decide between `@` and `'`, since both are just one character. That is, the user can decide whether or not to have appropriate syntax highlighting for the `relm4::view!` keywords.

## `'label` position

> Putting attributes always ahead of the widget or property has made parsing a breeze and is also very consistent for users.

If by “consistent” you mean that all attributes must always come before the method or type (widget), then your pseudocode is certainly consistent, but not necessarily correct or intuitive. For example, the following is intuitive:

~~~ rust
gtk::Label {
	'update if model.counter_changed()
	set_label: &format!("Count: {}", model.counter),
	
	'chain build()
	bind_property[&widget, "its-property"]: "own-property",
}
~~~

Let's say that `method: value` and `method = Type { }` are “assignments”. In this case it is correct because those `'labels` affect the assignments as a whole. That is, it expands as one would expect:

~~~ rust
if model.counter_changed() {
	// 'update uses the whole assignment:
	label.set_label(&format!("Count: {}", model.counter))
}

// 'chain adds build() to the end of the whole assignment.
label.bind_property("own-property", &widget, "its-property").build()
~~~

The following is not intuitive:

~~~ rust
gtk::Box {
	'name my_bin
	append: &adw::Bin { }, // first
	
	'wrap Some
	append: &adw::Bin { }, // second
}
~~~

By the same logic, it should expand as:

~~~ rust
let _unnamed_1 = adw::Bin::default(); // first
let _unnamed_2 = adw::Bin::default(); // second

// 'name is naming the whole assignment:
let my_bin = gtk_box.append(&_unnamed_1);

// 'wrap is funny:
Some(gtk_box.append(&_unnamed_2));
~~~

Instead, this is intuitive:

~~~ rust
gtk::Box {
	// what is being assigned is named, but not the assignment:
	append: &adw::Bin 'name my_bin { },
	
	// what is being assigned is wrapped in Some, but not the assignment:
	append: &adw::Bin 'wrap Some { },
}
~~~

An alternative (which I really dislike) would be:

~~~ rust
gtk::Box {
	append: 'name my_bin &adw::Bin { },
	append: 'wrap Some &adw::Bin { },
}
~~~

I feel weird having two types together (`Some` and `&adw::Bin`). Also, I think:

~~~ rust
gtk::Box {
	// saving lines of code like this:
	append: &adw::Bin 'name my_bin { },
	append: &adw::Bin 'wrap Some { },
	
	// is better than like this:
	'name my_bin append: &adw::Bin { },
	'wrap Some append: &adw::Bin { },
}
~~~

## Returned data

> ~~~ rust
> 'name my_page
> returns gtk::StackPage {}
> ~~~
> Note that returns is not an attribute anymore because IMO it doesn't make sense to make it an attribute.
> We should rather use it like a keyword.

I don't think of `'labels` as attributes, but as “`relm4::view!` keywords”, and in this case I think the best thing is to prevent a future problem. For example, it is possible to want to edit only the returned data. According to my proposal, it would be like this:

~~~ rust
property_expression: "folded" // we save a couple of { }
	'returns gtk::PropertyExpression 'name expression {
		bind["visible", glib::Object::NONE]: &back_button,
	},
~~~

According to your suggestion it would be:

~~~ rust
'name expression
property_expression: "folded" returns gtk::PropertyExpression {
	bind["visible", glib::Object::NONE]: &back_button,
},
~~~

At present there are no problems with your suggestion because `'name` is naming the entire assignment, which is precisely what it returns. But what if in the future we want to be able to name what is assigned, without having to edit what is assigned?

In the case of my proposal, the above would be explicit:

~~~ rust
property_expression: &format!("folded") -> String 'name property
	'returns gtk::PropertyExpression 'name expression {
		bind["visible", glib::Object::NONE]: &back_button,
	},
~~~

According to your suggestion, I could never name the expression without having to name the property:

~~~ rust
'name property 'name expression
property_expression: &format!("folded") -> String
	returns gtk::PropertyExpression {
		bind["visible", glib::Object::NONE]: &back_button,
	},
~~~

Unless a pair of braces are added, which is more lines of code and maybe a bit confusing because it looks like the String is being edited (it's not being edited because it's being assigned with `:` instead of `=`):

~~~ rust
'name property
property_expression: &format!("folded") -> String {
	'name expression
	returns gtk::PropertyExpression {
		bind["visible", glib::Object::NONE]: &back_button,
	},
},
~~~

I still think that my proposal is more idiomatic, and I take this opportunity to say that I also agree to continue using `->` instead of `as`.

## “Conditional Widgets”, or rather, Conditional Visible Child

Maybe it's best to improve the `'update` labels for this case:

~~~ rust
StackLikeWidget { // I think currently gtk::Stack and adw::Leaflet
	methods: "values",
	
	// the following only works if the widget has methods like set_visible_child:
	'update if model.condition() {
		gtk::Widget { }
	} else { // always has an else?
		gtk::Widget { }
	}
	
	// I'm not sure if this improvement applies to 'update_lazy:
	'update match value {
		"first"  => gtk::Widget { 'update_lazy method: model.lazy_counter },
		"second" => gtk::Widget {
			// another 'update improvement (also for 'update_lazy), if let support:
			'update if let Some(value) = model.get_counter()
			method: value
		},
	}
}
~~~

In this way we do not deceive the user anymore, because now he knows that there is a `gtk::Stack` or `adw::Leaflet` involved, and that the visible child is being changed in `update_view()`. Also avoid creating `#[attributes]` or `'labels` for each widget method, like the old `#[transition = "SlideRight"]`.

## Conditional Initialization (methods and now yes widgets)

> Additionally, nested conditional widgets make this approach more complicated.

I don't think so. The following:

~~~ rust
view! {
	gtk::Box {
		match model.create { // is different from 'update match <value> { }
			"bin" => adw::Bin { }
			"switch" => gtk::Switch { }
			_ => {
				set_spacing: 20, // methods are supported
				
				if let Some(number) = model.data {
					gtk::SpinButton { set_value: number as f64 }
				} // optional else
			}
		}
	}
}
~~~

Would expand to (never in `update_view()`):

~~~ rust
let _box = gtk::Box::default();
// conditional widgets must not be created here

match model.create {
	"bin" => {
		let _bin = adw::Bin::default();
		_box.append(&_bin);
	},
	"switch" => {
		let _switch = gtk::Switch::default();
		_box.append(&_switch);
	},
	_ => {
		_box.set_spacing(20);
		
		if let Some(number) = model.data {
			let _spin = gtk::SpinButton::default();
			_spin.set_value(number as f64);
			_box.append(&_spin),
		}
	}
}
~~~

It's basically the usual `if`, `if let` and `match`, and should support `'local`, `'local_ref`, `'chain`, `'returns` without `'name`, `'wrap`, probably `'template` and `'template child`, but not `'name`, ` 'update` and `'update_lazy`.

> If you want to keep the button in sync with DataType::Bool(value), you have to make sure that the user never uses another variant of DataType in their model

That's not my problem (or rather Relm4's), but the user's problem. If the user wants to change the data type but doesn't want to create widgets in `init()`, but in `view!` (because it's ideal), it's best to delete the current object and add an object with the desired type in the `FactoryContainer`.

In fact I am a user of this case, but since there is no support for conditional initialization, I am creating widgets manually in the `init()` of the factory. And in the view I have to do tricks like:

~~~ rust
view! {
	// a boolean to save code:
	is_switch = model.widget.downcast_ref::<gtk::Switch>().is_some() -> bool,
	// as you can see, I had to save the conditional widget in the model upcast to gtk::Widget
	
	// 'root adw::EntryRow would be better
	#[root] adw::EntryRow {
		set_title: &self.title,
		set_text: &self.id,
		
		add_suffix = &gtk::Box {
			// these assignments are only for when it is switch
			set_css_classes: if is_switch { &[] } else { &["linked"] },
			set_spacing: if is_switch { 6 } else { 0 },
			
			// again the widget in the model
			model.widget.as_ref() -> &gtk::Widget {
				set_valign: gtk::Align::Center,
			},
		}
	}
}
~~~

In a pseudocode you comment:

> ~~~ rust
> DataType::Bool(value) => gtk::Switch 'local my_switch {
> 	// How do you want to access or update this value???
> 	set_active: value,
> },
> ~~~

The `gtk::Switch` itself is supposed to update that value, I just haven't connected a signal to edit the model. On the other hand, data bindings could also be a solution.

**Comment by ejaa3** [comment] 2023-04-13 05:23
I just thought of this:

~~~ rust
// update always and initialize
'update set_label: &model.counter.to_string(),

// update always but not initialize
'update_lazy set_label: &model.counter.to_string(),

// update under a condition but initialize without it
'update if model.counter_changed() // or if let
set_label: &model.counter.to_string(),

// update under a condition but not initialize
'update_lazy if model.counter_changed() // or if let
set_label: &model.counter.to_string(),

// update and initialize under a condition (could be 'update_init)
'update_eval if model.counter_changed() // or if let
set_label: &model.counter.to_string(),

// with scope (should work with 'update_lazy and 'update_eval)
// the same descriptions as before
'update if model.counter_changed() { // or if let
	set_label: &model.counter.to_string(),
	set_tooltip_text: Some("hi"), // only methods
}, // there can be no else

// 'update_lazy and 'update_eval can use else and match
'update_eval if model.counter_changed() { // or if let | match
	set_label: &model.counter.to_string(), // only methods
	set_tooltip_text: Some("hi"), // only methods
}, // else if let | else if | else

// conditional visible child for stack-like widgets
// like gtk::Stack, adw::Leaflet and adw::ViewStack:
'update_child if model.counter == 1 { // if let | match
	gtk::Label 'name first_child { // only one widget per condition
		'returns { set_title: "page_title", }
		set_label: "1",
	} // cannot be an 'update_child_{lazy,eval}
} else { /* second page */ }

// conditional init:
if condition { // if let | match
	set_spacing: 10, // any number of methods per condition
	gtk::Label { set_label: "hello" }, // and any number of widgets
}
~~~

**Comment by AaronErhardt** [comment] 2023-04-13 06:32
#### Label position

> but not necessarily correct or intuitive

I don't see how your approach with sometimes before, sometimes after is correct or intuitive either. Basically, the logic would be to say "here's a name and that's the widget for it" and in the other case "here's the widget and that's the name for".
I get your point that it doesn't look great if you inline the labels like this `'label name append gtk::Box {...`. On the other side, I don't think the labels looks much better if inlined later. Arguably, using `append = 'wrap Some &gtk::Box {...` is the only somewhat consistent alternative because it has the labels before the widget.

I also wonder why you always format labels for properties with a new line, but inline all labels for widgets. In my opinion, a new line would always be better to read.

#### Returned widgets

I don't understand your examples. They both seem to be doing things that are not covered by the current macro and were not discussed before. My proposed solution would look like this:

```rust
add_page["my_page"] = gtk::Box {
    'name expression
    returns gtk::PropertyExpression {
        // Some properties
    }
},
```

If you want to actually name things that are returned by property assignments (which would be an entirely new feature), then using `'name some_name` would be just fine.

> But what if in the future we want to be able to name what is assigned, without having to edit what is assigned?

I don't understand what  you mean. You can't assign a name to a property in the first place because it has no variable to name and if you have a returned value that'd be the only thing to name.

I'm at work now, so I will continue this discussion later.

**Comment by AaronErhardt** [comment] 2023-04-13 15:17
### Conditional widget updates

Regarding conditional widgets, I don't see how your code examples would even be possible to implement. I've spent a lot of time working on the conditional syntax and I can tell you that the limitation of the current version (which is only that the widgets have to be created during initialization) doesn't come from nowhere. As soon as you update a property of an conditional widget, it must be either created during the initialization (which is the current solution) or lazily (which has it's own drawbacks, is quite hard to implement and does not have any practical advantage).


### Nested conditional widgets

> > Additionally, nested conditional widgets make this approach more complicated.

> I don't think so. The following:

Sure, if you never update anything it's quite simple. Static UIs are not a problem at all.

> That's not my problem (or rather Relm4's), but the user's problem

I disagree. For me, the conditional syntax has proven to remove a lot of ugly abstractions and made the code very easy to read and understand. It is a very useful and powerful feature that I don't want to remove.

The problem is just that you have a different use case, which isn't perfectly covered by the current syntax. You just assume because you don't need it nobody else needs it which is not the case. The current solution is obviously the most flexible approach, supporting both dynamic and static use cases. You have a static use case, so you might not want the (negligible) overhead of the current approach, but it is very easy to refactor your code to use it:

```rust
view! {
	// 'root adw::EntryRow would be better
	#[root] adw::EntryRow {
		set_title: &self.title,
		set_text: &self.id,
		
		add_suffix = &gtk::Box {
			// these assignments are only for when it is switch
			set_css_classes: if use_switch { &[] } else { &["linked"] },
			set_spacing: if use_switch { 6 } else { 0 },
			
			if use_switch {
                            gtk::Switch {}
                        } else {
                            OtherWidget {}
			},
		}
	}
}
```

However, I agree that we should have something for use cases like yours. A fully static initialization can have advantages in some scenarios, for example when initialization of different branches need data that cannot be offered to each branch at the same time.

```rust
match variable {
    Variant1(some_data) => {
        gtk::Label {
            // Currently not possible, because variant might not store Variant1
            // so some_data might not be available during initialization.
            // (update is fine because it just happens when the widget is visible)
            set_label: &some_data,
        }
    }
}
```

We should distinguish between two use cases:

1. Initialize only one widgets conditionally -> Use `Option<WidgetType>` in the `Widgets` struct -> Only run update logic `if let Some(widget) = conditional_widget`
2. Initialize all widgets -> Show and update them conditionally

Clearly, both have their strengths in static or dynamic use cases. Potentially, they could even use the same syntax, with one marked as `'dynamic` and one as `'static`.

**Comment by ejaa3** [comment] 2023-04-28 03:16
Greetings. After all I stopped using Relm4 and created my own procedural macro from scratch (couldn't believe macros were so simple). If you want take some ideas for Relm4: https://github.com/ejaa3/declarative

In case there is something pending, I will close the two issues that I have opened in Relm4 in a day, more or less.

**Closed** 2023-04-29 18:35 UTC
