### ISSUE TITLE
Fuzzy font on Windows

### ISSUE THREAD

**Issue by simalei** [Relm4/Relm4#634] opened 2024-05-14 16:34 UTC
I cloned repo and tried to run `alert` example and it had this issue.
I searched for possible solutions, and one of the most popular was enabling `gtk-hint-font-metric` yet it didn't help in that case.

![image](https://github.com/Relm4/Relm4/assets/65869620/6286a95b-861a-4320-be18-80285ae9afd8)

**Comment by AaronErhardt** [comment] 2024-05-14 18:36
This definitely looks bad, but I doubt that is has anything to do with Relm4. After all, Relm4 just uses gtk-rs which is just a Rust abstraction over GTK. It is very likely that an app written in C that directly uses GTK will also render incorrectly. This makes me wonder whether other GTK apps also look wrong on your system...

**Comment by simalei** [comment] 2024-05-15 07:21
Tried running example app using gtk4-rs directly, and it has the same problem. I guess it would be better to open this issue in gtk4-rs repo.

**Comment by AaronErhardt** [comment] 2024-05-15 07:38
Probably reporting the issue at the GTK repo is even better because gtk-rs just add a small layer for abstracting the C interface for Rust. This means there is effectively no relevant code added and the GTK library itself causes the issue. Maybe this has even been reported already: https://gitlab.gnome.org/GNOME/gtk/-/issues

**Comment by AaronErhardt** [comment] 2024-06-03 17:41
I'm closing this issue because the issue is not caused by Relm4.

**Closed by AaronErhardt** 2024-06-03 17:41 UTC
